### ISSUE TITLE
Tumbleweed xml won't build on latest kiwi

### ISSUE THREAD

**Issue by HouzuoGuo** [SUSE/kiwi-descriptions#13]
According to version 9.11.30, the tumbleweed xml has two issues:
- "error: value of attribute "schemaversion" is invalid; must be equal to "6.7""
- "KiwiTypeNotFound: build type vmx not found"

**Comment by davidcassany** [comment]
Hi @HouzuoGuo,

> "error: value of attribute "schemaversion" is invalid; must be equal to "6.7""

Sorry for the inconvenience, you are right, KIWI is about to be updated to 9.12.0 and it will support schemaversion 6.8.

> "KiwiTypeNotFound: build type vmx not found"

I suspect this is not an error, the tumbleweed description image file only includes an iso image example, thus there is no vmx definition. It can be easily added by following the leap 42.3 example, where there are vmx and oem image definitions.
