### ISSUE TITLE
Debian stretch descriptions => debootstrap script not found

### ISSUE THREAD

**Issue by dfabbeloos** [SUSE/kiwi-descriptions#38]
Building the debian stretch descriptions yields the error below. 
Any ideas?

> kiwi --version
KIWI (next generation) version 9.17.37

> sudo kiwi-ng --type vmx system build \
    --description kiwi-descriptions/suse/x86_64/debian-stretch-JeOS \
    --target-dir /tmp/myimage

yields the following output

[ INFO    ]: 23:36:22 | Loading XML description
[ INFO    ]: 23:36:22 | --> loaded deb1/config.xml
[ INFO    ]: 23:36:22 | --> Selected build type: vmx
[ INFO    ]: 23:36:22 | Preparing new root system
[ INFO    ]: 23:36:22 | Setup root directory: 
[ INFO    ]: 23:36:22 | Setting up repository http://ftp.halifax.rwth-aachen.de/debian
[ INFO    ]: 23:36:22 | --> Type: apt-deb
[ INFO    ]: 23:36:22 | --> Translated: http://ftp.halifax.rwth-aachen.de/debian
[ INFO    ]: 23:36:22 | --> Alias: 11d73968d25aec7118b11e0a8762028d
[ INFO    ]: 23:36:22 | Setting up repository obs://Virtualization:Appliances:Builder/Debian_9.0
[ INFO    ]: 23:36:22 | --> Type: apt-deb
[ INFO    ]: 23:36:22 | --> Translated: http://download.opensuse.org/repositories/Virtualization:/Appliances:/Builder/Debian_9.0/
[ INFO    ]: 23:36:22 | --> Alias: 0f57536092f42cc4707125c52ef87cb8
[ INFO    ]: 23:36:22 | Using package manager backend: apt-get
[ INFO    ]: 23:36:22 | Installing bootstrap packages
[ INFO    ]: 23:36:22 | --> collection type: onlyRequired
[ INFO    ]: 23:36:22 | --> package: apt-get
[ INFO    ]: 23:36:22 | --> package: grub2
[ INFO    ]: 23:36:22 | --> package: initramfs-tools
[ INFO    ]: 23:36:22 | --> package: linux-image-amd64
[ ERROR   ]: 23:36:22 | KiwiDebootstrapError: debootstrap script for stretch distribution not found
[ INFO    ]: 23:36:22 | Cleaning up SystemPrepare instance

**Comment by schaefi** [comment]
On your host machine (the one you run kiwi on) there must be a working debootstrap installed for the target you want to build. iirc Debian provides debootstrap template packages for every distro. In your case it seems the debootstrap data for stretch is not existing. This could have several reasons:

1. Your build host is not Debian based e.g a suse or fedora build host. In this case you need to install debootstrap and the stretch setup

2. Your build host is Debian based but not stretch. In that case just install the debootstrap stretch setup.

Hope that helps

**Comment by dfabbeloos** [comment]
Thanks for the quick solution. 

The build host is opensuse-tumbleweed (20190430), so running the following commands
fixed the problem
```
> zypper in debootstrap
> zypper in dpkg
```

Thx!
