### ISSUE TITLE
[help] KiwiCommandError: chroot: stderr: /usr/share/plymouth/themes/breeze/breeze.plymouth does not exist

### ISSUE THREAD

**Issue by kevinsmia1939** [SUSE/kiwi-descriptions#40]
I just tried using kiwi for the first time to build an image.
I ran into this error:
[ ERROR   ]: 01:12:39 | KiwiCommandError: chroot: stderr: /usr/share/plymouth/themes/breeze/breeze.plymouth does not exist
, stdout: (no output on stdout)

I make sure I have /usr/share/plymouth/themes/breeze/breeze.plymouth in the directory, I install it from the repo normally.

I change the plymouth bootsplash accordinly config.xml 

```
  <bootsplash-theme>breeze</bootsplash-theme>
   <bootloader-theme>breeze</bootloader-theme>
```

What could have cause this. Thank you.

openSUSE Tumbleweed

The full log is

sudo kiwi-ng --type iso system build --description /home/user/Desktop/kiwi-descriptions-master/suse/x86_64/suse-tumbleweed-JeOS/ --target-dir /home/user/Desktop/mydistro

[sudo] password for root: 
[ INFO    ]: 01:09:19 | Loading XML description
[ INFO    ]: 01:09:19 | --> loaded /home/kev/Desktop/kiwi-descriptions-master/suse/x86_64/suse-tumbleweed-JeOS/config.xml
[ INFO    ]: 01:09:19 | --> Selected build type: iso
[ INFO    ]: 01:09:19 | Preparing new root system
[ INFO    ]: 01:09:19 | Setup root directory: /home/kev/Desktop/mydistro/build/image-root
[ INFO    ]: 01:09:21 | Setting up repository obs://Virtualization:Appliances:Builder/Factory
[ INFO    ]: 01:09:21 | --> Type: rpm-md
[ INFO    ]: 01:09:21 | --> Priority: 1
[ INFO    ]: 01:09:21 | --> Translated: http://download.opensuse.org/repositories/Virtualization:/Appliances:/Builder/Factory/
[ INFO    ]: 01:09:21 | --> Alias: kiwi
[ ERROR   ]: 01:09:21 | KiwiCommandError: zypper: stderr: System management is locked by the application with pid 16253 (/usr/bin/ruby.ruby2.6).
Close this application before trying again.
, stdout: (no output on stdout)
[ INFO    ]: 01:09:21 | Cleaning up SystemPrepare instance
[ WARNING ]: 01:09:21 | remove_hierarchy: path /home is protected
kev@linux-u51f:~> sudo kiwi-ng --type iso system build --description /home/kev/Desktop/kiwi-descriptions-master/suse/x86_64/suse-tumbleweed-JeOS/ --target-dir /home/kev/Desktop/mydistro2
[ INFO    ]: 01:09:41 | Loading XML description
[ INFO    ]: 01:09:41 | --> loaded /home/kev/Desktop/kiwi-descriptions-master/suse/x86_64/suse-tumbleweed-JeOS/config.xml
[ INFO    ]: 01:09:41 | --> Selected build type: iso
[ INFO    ]: 01:09:41 | Preparing new root system
[ INFO    ]: 01:09:41 | Setup root directory: /home/kev/Desktop/mydistro2/build/image-root
[ INFO    ]: 01:09:42 | Setting up repository obs://Virtualization:Appliances:Builder/Factory
[ INFO    ]: 01:09:42 | --> Type: rpm-md
[ INFO    ]: 01:09:42 | --> Priority: 1
[ INFO    ]: 01:09:42 | --> Translated: http://download.opensuse.org/repositories/Virtualization:/Appliances:/Builder/Factory/
[ INFO    ]: 01:09:42 | --> Alias: kiwi
[ INFO    ]: 01:09:43 | Setting up repository http://download.opensuse.org/tumbleweed/repo/oss
[ INFO    ]: 01:09:43 | --> Type: None
[ INFO    ]: 01:09:43 | --> Translated: http://download.opensuse.org/tumbleweed/repo/oss
[ INFO    ]: 01:09:43 | --> Alias: Tumbleweed
[ INFO    ]: 01:09:43 | Using package manager backend: zypper
[ INFO    ]: 01:09:43 | Installing bootstrap packages
[ INFO    ]: 01:09:43 | --> collection type: onlyRequired
[ INFO    ]: 01:09:43 | --> package: ca-certificates
[ INFO    ]: 01:09:43 | --> package: cracklib-dict-full
[ INFO    ]: 01:09:43 | --> package: filesystem
[ INFO    ]: 01:09:43 | --> package: glibc-locale
[ INFO    ]: 01:09:43 | --> package: openSUSE-release
[ INFO    ]: 01:09:43 | --> package: udev
[ INFO    ]: 01:09:43 | --> package: zypper
[ INFO    ]: Processing: [########################################] 100%
[ INFO    ]: 01:11:08 | Installing system (chroot) for build type: iso
[ INFO    ]: 01:11:08 | --> collection type: onlyRequired
[ INFO    ]: 01:11:08 | --> package: bash-completion
[ INFO    ]: 01:11:08 | --> package: dhcp-client
[ INFO    ]: 01:11:08 | --> package: dracut-kiwi-live
[ INFO    ]: 01:11:08 | --> package: fontconfig
[ INFO    ]: 01:11:08 | --> package: fonts-config
[ INFO    ]: 01:11:08 | --> package: gfxboot
[ INFO    ]: 01:11:08 | --> package: grub2
[ INFO    ]: 01:11:08 | --> package: grub2-branding-openSUSE
[ INFO    ]: 01:11:08 | --> package: grub2-i386-pc
[ INFO    ]: 01:11:08 | --> package: ifplugd
[ INFO    ]: 01:11:08 | --> package: iproute2
[ INFO    ]: 01:11:08 | --> package: iputils
[ INFO    ]: 01:11:08 | --> package: kernel-default
[ INFO    ]: 01:11:08 | --> package: less
[ INFO    ]: 01:11:08 | --> package: lvm2
[ INFO    ]: 01:11:08 | --> package: openssh
[ INFO    ]: 01:11:08 | --> package: parted
[ INFO    ]: 01:11:08 | --> package: patterns-openSUSE-base
[ INFO    ]: 01:11:08 | --> package: plymouth
[ INFO    ]: 01:11:08 | --> package: plymouth-branding-openSUSE
[ INFO    ]: 01:11:08 | --> package: plymouth-dracut
[ INFO    ]: 01:11:08 | --> package: syslinux
[ INFO    ]: 01:11:08 | --> package: tar
[ INFO    ]: 01:11:08 | --> package: timezone
[ INFO    ]: 01:11:08 | --> package: vim
[ INFO    ]: 01:11:08 | --> package: which
[ INFO    ]: Processing: [########################################] 100%
[ INFO    ]: 01:12:38 | Creating .profile environment
[ INFO    ]: 01:12:38 | Importing Image description to system tree
[ INFO    ]: 01:12:38 | --> Importing state XML description as image/config.xml
[ INFO    ]: 01:12:38 | --> Importing config.sh script as image/config.sh
[ INFO    ]: 01:12:38 | --> Importing script helper functions
[ INFO    ]: 01:12:38 | Copying user defined files to image tree
[ INFO    ]: 01:12:39 | Setting up user root
[ INFO    ]: 01:12:39 | --> Modifying user: root [root]
[ INFO    ]: 01:12:39 | Setting up keytable: us
[ INFO    ]: 01:12:39 | Setting up locale: en_US
[ ERROR   ]: 01:12:39 | KiwiCommandError: chroot: stderr: /usr/share/plymouth/themes/breeze/breeze.plymouth does not exist
, stdout: (no output on stdout)
[ INFO    ]: 01:12:39 | Cleaning up SystemPrepare instance
[ WARNING ]: 01:12:40 | remove_hierarchy: path /home is protected

**Comment by schaefi** [comment]
This is because of a change in the TW/Factory distribution. SUSE now uses the upstream bgrt theme.
I've update the respective example description.

If you use kiwi for the first time I suggest to follow this guide:

* https://opensource.suse.com/kiwi/quickstart.html

Hope that helps

**Comment by kevinsmia1939** [comment]
It fixed now, thanks.
