### ISSUE TITLE
What is 70-persistent-net.rules in root/etc/udev/rules.d for?

### ISSUE THREAD

**Issue by kevinsmia1939** [SUSE/kiwi-descriptions#58]
I have had problem with USB wifi dongle not finding any Network at boot, until it is unplugged and plug back in.

Until I delete 70-persistent-net.rules and rebuild the live image, it work properly again. I first I thought it was NetworkManager bug which I ask here:
https://forums.opensuse.org/showthread.php/538063-I-can-only-connect-to-internet-when-un-plug-plug-the-USB-wifi-card-(live-ISO-build-with-KIWI)

Which did not find any clue until I randomly try to delete 70-persistent-net.rules.
Thanks.

**Comment by davidcassany** [comment]
@kevinsmia1939 the 70-persistent-net.rules is just an udev rule to rename the network interface to a known and persistent interface name, in this case `lan0`. Probably this udev rule changes the name of the wifi interface causing some issue Network Manager... This rule I'd say is mostly devoted to ethernet interfaces and it is helpful when you'd like to provide some static configuration of the ethernet interface without having to guess the default name of it, as you can expect it to be called `lan0`.

Does your system include an enthernet interface? How are the interfaces called after booting with the 70-presistent-net.rules active and including the USB dongle device? In any case it should not cause issues deleting the `70-persistnet-net.rules`, at worst you'll notice the interfaces might be named different depending on the hardware the live image is running on. So, if you do not have any specific static network configuration based on `lan0` interface, deleting the udev rule is safe.

**Comment by kevinsmia1939** [comment]
nmcli d
DEVICE       TYPE      STATE        CONNECTION 
wlp0s26u1u1  wifi      connected    VM2080987  
virbr0           bridge    connected    virbr0     
enp3s0       ethernet  unavailable  --         
lo              loopback  unmanaged    --         
virbr0-nic     tun       unmanaged    --    

I don't have any ethernet active, but even so I think it is called enp3s0. Anyway I remove the 70-persistnet-net.rules, so it doesn't matter now.
