### ISSUE TITLE
systemd-firstboot not available for Ubuntu

### ISSUE THREAD

**Issue by ghost** [SUSE/kiwi-descriptions#62]
I am trying to create an ubuntu based oem image by porting [ubuntu-xenial-JeOS/config.xml](https://github.com/OSInside/kiwi-descriptions/blob/master/ubuntu/x86_64/ubuntu-xenial-JeOS/config.xml) to work with ubuntu 18.04.
The problem is kiwi trying to run systemd-firstboot inside the chroot, which does not seem to be available for ubuntu.

```
INFO: 14:44:29 | Setting up keytable: us
DEBUG: 14:44:29 | EXEC: [chroot /tmp/myimage/build/image-root systemd-firstboot --help]
DEBUG: 14:44:29 | EXEC: Failed with stderr: chroot: failed to run command ‘systemd-firstboot’: No such file or directory
, stdout: (no output on stdout)
WARNING: 14:44:29 | Could not parse systemd-firstboot output
WARNING: 14:44:29 | keyboard setup skipped no capable systemd-firstboot or etc/sysconfig/keyboard found
INFO: 14:44:29 | Setting up locale: en_US
DEBUG: 14:44:29 | EXEC: [chroot /tmp/myimage/build/image-root systemd-firstboot --help]
DEBUG: 14:44:29 | EXEC: Failed with stderr: chroot: failed to run command ‘systemd-firstboot’: No such file or directory
, stdout: (no output on stdout)
WARNING: 14:44:29 | Could not parse systemd-firstboot output
DEBUG: 14:44:29 | "plymouth-set-default-theme": in paths "/tmp/myimage/build/image-root/usr/sbin:/tmp/myimage/build/image-root/usr/bin:/tmp/myimage/build/image-root/sbin:/tmp/myimage/build/image-root/bin" exists: "False" mode match: not checked
INFO: 14:44:29 | Setting up timezone: UTC
DEBUG: 14:44:29 | EXEC: [chroot /tmp/myimage/build/image-root systemd-firstboot --help]
DEBUG: 14:44:29 | EXEC: Failed with stderr: chroot: failed to run command ‘systemd-firstboot’: No such file or directory
, stdout: (no output on stdout)
WARNING: 14:44:29 | Could not parse systemd-firstboot output
```
Is there any way to not depend on systemd-firstboot?

**Comment by davidcassany** [comment]
I believe this is not the actual problem you are facing, note that those are only `WARNING` messages. KIWI uses the systemd-firtboot utility as a first option, other strategies are followed when `systemd-firstboot` is not there or it is a version not having the capabilities KIWI expects.

Are you experiencing failures at boot time or at build time? Is KIWI ending the build procedure? If the image is not building complete build logs are helpful.

**Comment by ghost** [comment]
Thank you.
I was experiencing other failures, but I thought they were a result of `systemd-firstboot`. I will look into that.

**Comment by ghost** [comment]
I could need some additional help.

The Build fails at `Creating generic dracut initrd archive` when it tries to install `btrfs` and `btrfsck`.
Which seems odd for me, since I specified `ext4` in the oem definition, so there should be no need for btrfs(?).

This is the config.xml:
```xml
<?xml version="1.0" encoding="utf-8"?>

<!-- The line below is required in order to use the multibuild OBS features -->
<!-- OBS-Profiles: @BUILD_FLAVOR@ -->

<image schemaversion="6.9" name="LimeJeOS-Ubuntu-18.04">
    <description type="system">
        <author>Marcus Schaefer</author>
        <contact>ms@suse.com</contact>
        <specification>vmx disk test build for Ubuntu</specification>
    </description>
    <preferences>
        <version>1.16.4</version>
        <packagemanager>apt-get</packagemanager>
        <bootsplash-theme>sabily</bootsplash-theme>
        <bootloader-theme>ubuntu-mate</bootloader-theme>
        <locale>en_US</locale>
        <keytable>us</keytable>
        <timezone>UTC</timezone>
        <rpm-check-signatures>false</rpm-check-signatures>
        <type image="iso" flags="overlay" hybridpersistent_filesystem="ext4" hybridpersistent="true"/>
        <type image="vmx" filesystem="ext4" bootloader="grub2" kernelcmdline="console=ttyS0 splash"/>
        <type image="oem" filesystem="ext4" initrd_system="dracut" bootloader="grub2" firmware="efi" installiso="true">
            <oemconfig>
                <oem-swap>true</oem-swap>
                <oem-device-filter>/dev/ram</oem-device-filter>
                <oem-multipath-scan>false</oem-multipath-scan>
            </oemconfig>
        </type>
    </preferences>
    <users>
        <user password="1234" home="/root" name="root" groups="root"/>
    </users>
    <repository type="apt-deb" repository_gpgcheck="false">
        <source path="obs://Virtualization:Appliances:Staging/xUbuntu_18.04"/>
    </repository>
    <repository type="apt-deb" alias="Bionic-security" distribution="bionic-security" components="main multiverse restricted universe" repository_gpgcheck="false">
        <source path="http://security.ubuntu.com/ubuntu"/>
    </repository>
    <repository type="apt-deb" alias="Bionic-updates" distribution="bionic-updates" components="main multiverse restricted universe" repository_gpgcheck="false">
        <source path="http://us.archive.ubuntu.com/ubuntu/"/>
    </repository>
    <repository type="apt-deb" alias="Bionic" distribution="bionic" components="main multiverse restricted universe" repository_gpgcheck="false">
        <source path="http://us.archive.ubuntu.com/ubuntu/"/>
    </repository>
    <packages type="oem">
        <package name="dracut-kiwi-oem-repart"/>
        <package name="dracut-kiwi-oem-dump"/>
    </packages>
    <packages type="image">
        <package name="grub2-themes-ubuntu-mate"/>
        <package name="plymouth-theme-sabily"/>
        <package name="plymouth"/>
        <package name="linux-generic"/>
        <package name="isolinux"/>
        <package name="syslinux"/>
        <package name="syslinux-common"/>
        <package name="dracut"/>
        <package name="grub2"/>
        <package name="init"/>
        <package name="gnupg"/>
        <package name="iproute2"/>
        <package name="iptables"/>
        <package name="iputils-ping"/>
        <package name="ifupdown"/>
        <package name="isc-dhcp-client"/>
        <package name="netbase"/>
        <package name="dbus"/>
    </packages>
    <packages type="iso">
        <package name="dracut-kiwi-live"/>
    </packages>
    <packages type="bootstrap">
        <package name="initramfs-tools"/>
        <package name="linux-generic"/>
        <package name="grub2"/>
    </packages>
</image>
```

This is the relevant part of the build log.
<details>
DEBUG: 15:44:53 | EXEC: [chroot /tmp/myimage/build/image-root dracut --verbose --no-hostonly --no-hostonly-cmdline --xz --install /.profile --add  kiwi-repart  --omit  multipath  --install /config.partids LimeJeOS-Ubuntu-18.04.x86_64-1.16.4.initrd.xz 4.15.0-88-generic]

DEBUG: 15:45:45 | dracut: Executing: /usr/bin/dracut --verbose --no-hostonly --no-hostonly-cmdline --xz --install /.profile --add " kiwi-repart " --omit " multipath " --install /config.partids LimeJeOS-Ubuntu-18.04.x86_64-1.16.4.initrd.xz 4.15.0-88-generic

dracut: dracut module 'bootchart' will not be installed, because command '/sbin/bootchartd' could not be found!

dracut: dracut module 'caps' will not be installed, because command 'capsh' could not be found!


dracut: dracut module 'modsign' will not be installed, because command 'keyctl' could not be found!

dracut: dracut module 'busybox' will not be installed, because command 'busybox' could not be found!

dpkg-architecture: warning: cannot determine CC system type, falling back to default (native compilation)

dracut: dracut module 'plymouth' will not be installed, because command 'plymouth-set-default-theme' could not be found!

dracut: dracut module 'btrfs' will not be installed, because command 'btrfs' could not be found!

dracut: dracut module 'dmraid' will not be installed, because command 'dmraid' could not be found!

dracut: dracut module 'multipath' will not be installed, because it's in the list to be omitted!

dracut: dracut module 'cifs' will not be installed, because command 'mount.cifs' could not be found!

dracut: dracut module 'fcoe' will not be installed, because command 'dcbtool' could not be found!

dracut: dracut module 'fcoe' will not be installed, because command 'fipvlan' could not be found!

dracut: dracut module 'fcoe' will not be installed, because command 'lldpad' could not be found!

dracut: dracut module 'fcoe' will not be installed, because command 'fcoemon' could not be found!

dracut: dracut module 'fcoe' will not be installed, because command 'fcoeadm' could not be found!

dracut: dracut module 'fcoe-uefi' will not be installed, because command 'dcbtool' could not be found!

dracut: dracut module 'fcoe-uefi' will not be installed, because command 'fipvlan' could not be found!

dracut: dracut module 'fcoe-uefi' will not be installed, because command 'lldpad' could not be found!

dracut: dracut module 'iscsi' will not be installed, because command 'iscsistart' could not be found!

dracut: dracut module 'iscsi' will not be installed, because command 'iscsi-iname' could not be found!

dracut: dracut module 'nbd' will not be installed, because command 'nbd-client' could not be found!

dracut: 95nfs: Could not find any command of 'rpcbind portmap'!

dracut: dracut module 'ssh-client' will not be installed, because command 'ssh' could not be found!

dracut: dracut module 'ssh-client' will not be installed, because command 'scp' could not be found!

dracut: dracut module 'biosdevname' will not be installed, because command 'biosdevname' could not be found!

dracut: *** Including module: bash ***

dracut: *** Including module: dash ***

dracut: *** Including module: systemd ***

dracut: *** Including module: systemd-initrd ***

dracut: *** Including module: network ***

dracut: *** Including module: ifcfg ***

dracut: *** Including module: aufs ***

dracut: *** Including module: crypt ***

dracut: *** Including module: dm ***

dracut: Skipping udev rule: 10-dm.rules

dracut: Skipping udev rule: 13-dm-disk.rules

dracut: Skipping udev rule: 64-device-mapper.rules

dracut: *** Including module: kernel-modules ***

dracut: *** Including module: kernel-network-modules ***

dracut: *** Including module: kiwi-repart ***

dracut: *** Including module: lvm ***

dracut: Skipping udev rule: 11-dm-lvm.rules

dracut: Skipping udev rule: 69-dm-lvm-metad.rules

dracut: Skipping udev rule: 64-device-mapper.rules

dracut: *** Including module: mdraid ***

dracut: Skipping udev rule: 64-md-raid.rules

dracut: *** Including module: overlay-root ***

dracut: *** Including module: qemu ***

dracut: *** Including module: qemu-net ***

dracut: *** Including module: lunmask ***

dracut: *** Including module: resume ***

dracut: *** Including module: rootfs-block ***

dracut: *** Including module: terminfo ***

dracut: *** Including module: udev-rules ***

dracut: Skipping udev rule: 40-redhat.rules

dracut: Skipping udev rule: 91-permissions.rules

dracut: Skipping udev rule: 80-drivers-modprobe.rules

dracut: *** Including module: dracut-systemd ***

dracut: *** Including module: usrmount ***

dracut: *** Including module: base ***

dracut: *** Including module: fs-lib ***

dracut: *** Including module: kiwi-lib ***

dracut-install: ERROR: installing 'btrfs'

dracut-install: ERROR: installing 'btrfsck'

dracut: FAILED: /usr/lib/dracut/dracut-install -D /var/tmp/dracut.9VpPT2/initramfs -a blkid blockdev parted dd mkdir rmdir grep cut tail head tr bc basename partprobe sfdisk sgdisk mkswap readlink lsblk btrfs xfs_growfs resize2fs e2fsck btrfsck xfs_repair vgs vgchange lvextend lvcreate lvresize pvresize mdadm cryptsetup dialog pv curl xz dmsetup


dracut: *** Including module: shutdown ***

dracut: *** Including modules done ***

dracut-install: Failed to find module 'crc32c'

dracut: FAILED:  /usr/lib/dracut/dracut-install -D /var/tmp/dracut.9VpPT2/initramfs --kerneldir /lib/modules/4.15.0-88-generic/ -m crc32c

dracut: *** Installing kernel module dependencies ***

dracut: *** Installing kernel module dependencies done ***

dracut: *** Resolving executable dependencies ***

dracut: *** Resolving executable dependencies done***

dracut: *** Stripping files ***

dracut: *** Stripping files done ***

dracut: *** Generating early-microcode cpio image ***

dracut: *** Constructing AuthenticAMD.bin ****

dracut: *** Constructing GenuineIntel.bin ****

dracut: *** Store current command line parameters ***

dracut: *** Creating image file '/LimeJeOS-Ubuntu-18.04.x86_64-1.16.4.initrd.xz' ***

dracut: Image: /var/tmp/dracut.9VpPT2/initramfs.img: 42M

dracut: ========================================================================

dracut: Early CPIO image

dracut: ========================================================================

dracut: drwxr-xr-x   1 root     root            0 Mar  9 14:45 .

dracut: -rw-r--r--   1 root     root            2 Mar  9 14:45 early_cpio

dracut: drwxr-xr-x   1 root     root            0 Mar  9 14:45 kernel

dracut: drwxr-xr-x   1 root     root            0 Mar  9 14:45 kernel/x86

dracut: drwxr-xr-x   1 root     root            0 Mar  9 14:45 kernel/x86/microcode

dracut: -rw-r--r--   1 root     root        30546 Mar  9 14:45 kernel/x86/microcode/AuthenticAMD.bin

dracut: -rw-r--r--   1 root     root      2960384 Mar  9 14:45 kernel/x86/microcode/GenuineIntel.bin

dracut: ========================================================================

dracut: Version: dracut-

dracut: 

dracut: Arguments: --verbose --no-hostonly --no-hostonly-cmdline --xz --install '/.profile' --add ' kiwi-repart ' --omit ' multipath ' --install '/config.partids'


dracut: 

dracut: dracut modules:

dracut: bash

dracut: dash

dracut: systemd

dracut: systemd-initrd

dracut: network

dracut: ifcfg

dracut: aufs

dracut: crypt

dracut: dm

dracut: kernel-modules

dracut: kernel-network-modules

dracut: kiwi-repart

dracut: lvm

dracut: mdraid

dracut: overlay-root

dracut: qemu

dracut: qemu-net

dracut: lunmask

dracut: resume

dracut: rootfs-block

dracut: terminfo

dracut: udev-rules

dracut: dracut-systemd

dracut: usrmount

dracut: base

dracut: fs-lib

dracut: kiwi-lib

dracut: shutdown

dracut: ========================================================================

dracut: drwxr-xr-x   1 root     root            0 Mar  9 14:44 .

dracut: -rw-r--r--   1 root     root          492 Mar  9 14:44 .profile

dracut: crw-r--r--   1 root     root       5,   1 Mar  9 14:44 dev/console

// I omitted the long list of files here

dracut: ========================================================================

dracut: *** Creating initramfs image file '/LimeJeOS-Ubuntu-18.04.x86_64-1.16.4.initrd.xz' done ***

stat: cannot read table of mounted file systems: No such file or directory


DEBUG: 15:45:45 | EXEC: [mv /tmp/myimage/build/image-root/LimeJeOS-Ubuntu-18.04.x86_64-1.16.4.initrd.xz /tmp/myimage]

INFO: 15:45:45 | --> initrd archive as initramfs-4.15.0-88-generic.img

DEBUG: 15:45:45 | EXEC: [mv /tmp/myimage/LimeJeOS-Ubuntu-18.04.x86_64-1.16.4.initrd.xz /tmp/myimage/build/image-root/boot/initramfs-4.15.0-88-generic.img]

INFO: 15:45:45 | Creating grub2 bootloader configuration

DEBUG: 15:45:45 | EXEC: [blkid /dev/mapper/loop0p4 -s UUID -o value]

DEBUG: 15:45:46 | EXEC: [blkid /dev/mapper/loop0p4 -s UUID -o value]

INFO: 15:45:46 | Creating grub2 bootloader images

DEBUG: 15:45:46 | EXEC: [mkdir -p /tmp/myimage/build/image-root/boot/efi/EFI/BOOT]

DEBUG: 15:45:46 | EXEC: [mkdir -p /tmp/myimage/build/image-root/boot/grub/fonts]

DEBUG: 15:45:46 | EXEC: [cp /tmp/myimage/build/image-root/usr/share/grub/unicode.pf2 /tmp/myimage/build/image-root/boot/grub/fonts]

DEBUG: 15:45:46 | EXEC: [rsync -a /tmp/myimage/build/image-root/boot/grub/themes/ubuntu-mate /tmp/myimage/build/image-root/boot/grub/themes]

DEBUG: 15:45:46 | EXEC: [rsync -a --exclude /*.module /tmp/myimage/build/image-root/usr/lib/grub/i386-pc/ /tmp/myimage/build/image-root/boot/grub/i386-pc]

INFO: 15:45:46 | --> Creating unsigned efi image

ERROR: 15:45:46 | KiwiBootLoaderGrubDataError: grub path x86_64-efi not found in ['/tmp/myimage/build/image-root/usr/share/grub2/x86_64-efi', '/tmp/myimage/build/image-root/usr/lib/grub2/x86_64-efi', '/tmp/myimage/build/image-root/usr/share/grub/x86_64-efi', '/tmp/myimage/build/image-root/usr/lib/grub/x86_64-efi']

INFO: 15:45:46 | Cleaning up BootImageDracut instance

INFO: 15:45:46 | Cleaning up Disk instance

DEBUG: 15:45:46 | EXEC: [dmsetup remove /dev/mapper/loop0p1]

DEBUG: 15:45:46 | EXEC: [dmsetup remove /dev/mapper/loop0p2]

DEBUG: 15:45:46 | EXEC: [dmsetup remove /dev/mapper/loop0p3]

DEBUG: 15:45:46 | EXEC: [dmsetup remove /dev/mapper/loop0p4]

INFO: 15:45:46 | Cleaning up LoopDevice instance

DEBUG: 15:45:46 | EXEC: [losetup -d /dev/loop0]

INFO: 15:45:46 | Cleaning up BootLoaderConfigGrub2 instance

INFO: 15:45:46 | Cleaning up BootImageDracut instance
</details>

**Comment by ghost** [comment]
Turns out I was missing `btrfs-progs`.
