### ISSUE TITLE
openSUSE Leap 42.3 repository ends up in "HTTP 404: not found"

### ISSUE THREAD

**Issue by rakoenig** [SUSE/kiwi-descriptions#8]
The repostiory settings for Leap-42.3-JeOS worked perfectly in August and today all I get is a 404 for that reposotory. 

```
<repository type="rpm-md" imageinclude="true">
        <source path="obs://openSUSE:Leap:42.3/standard"/>
</repository>
```

Noticed that sometimes we even end up in "HTTP500 Server error". What's going on?

**Comment by davidcassany** [comment]
http://download.opensuse.org is having some maintenance issues today afternoon, I think we just need to be patient for the infrastructure team to solve it.

**Comment by rakoenig** [comment]
Yup, functionality is back. Issue closed.
