### ISSUE TITLE
KiwiTypeNotFound: build type oem not found - 0x7fdb3cf48898

### ISSUE THREAD

**Issue by givemethatpie** [SUSE/kiwi-descriptions#81]
Hi all,

I am having a few issues building a Kiwi-ng openSUSE 15.2 oem/expandable disk image. I have made a Live ISO no problems, however when making the oem disk I am getting the following error:

`KiwiTypeNotFound: build type oem not found in [<kiwi.xml_parse.description object at 0x7fdb3cf48898>]
`

My config.xml has the following parameters associated with oem/expandable disks:

`        <profile name="Disk" description="Expandable Disk image"/>
`

`    <preferences profiles="Disk">
        <type image="oem" filesystem="ext4" initrd_system="dracut" installiso="true" bootloader="grub2" kernelcmdline="splash" firmware="efi" format="vmdk">
            <oemconfig>
                <oem-systemsize>2048</oem-systemsize>
                <oem-swap>true</oem-swap>
                <oem-device-filter>/dev/ram</oem-device-filter>
                <oem-multipath-scan>false</oem-multipath-scan>
                <oem-resize>false</oem-resize>
            </oemconfig>
        </type>
    </preferences>
`

`    <packages type="oem">
        <package name="gfxboot-branding-openSUSE"/>
    </packages>
`

Any help would be great, thanks!

**Comment by schaefi** [comment]
Have you selected the profile that contains your oem image type ?

```
$ kiwi-ng --profile Disk --type oem system build ...
```

Also note if you manage a ```<type>``` in a profile (Disk) and that profile collects only one type you don't have to select it.

```
$ kiwi-ng --profile Disk system build ...
```

**Comment by givemethatpie** [comment]
Hi there,

 

Thank you for your response. The `kiwi-ng --profile Disk` additional parameter has resolved the issue

 

Thanks again, much appreciated!

 

 
 

Sent: Tuesday, February 02, 2021 at 10:21 AM

**Comment by schaefi** [comment]
Happy to hear that, thanks for the feedback.

btw, we are also reachable here: https://app.element.io/#/room/#kiwi:matrix.org
