### ISSUE TITLE
opensuse tumbleweed keeps getting these errors when trying to turn it into a iso and creates a folder instead

### ISSUE THREAD

**Issue by NerdyBraixen** [SUSE/kiwi-descriptions#88]
![Captureh](https://user-images.githubusercontent.com/86548927/123536413-0a12fe00-d6df-11eb-883b-2640ed894aa6.PNG)
![Captureh2](https://user-images.githubusercontent.com/86548927/123536414-0aab9480-d6df-11eb-9d88-13c11e4f1b9a.PNG)

**Comment by schaefi** [comment]
Is now fixed with https://github.com/OSInside/kiwi-descriptions/commit/15f971a12a63d7a1afc30033327130051ffba06e
