### ISSUE TITLE
Please provide kiwi ng description file for centos-stream-8

### ISSUE THREAD

**Issue by koteswara-kelam** [SUSE/kiwi-descriptions#89]
Similar to https://github.com/OSInside/kiwi-descriptions/blob/master/centos/x86_64/centos-09.0/config.xml, I want description file for CentOS-Stream-8. Please help.

**Comment by koteswara-kelam** [comment]
As CentOS 8 has reached EOL, I want to move to CentOS Stream 8.

**Comment by schaefi** [comment]
@Conan-Kudo has updated all descriptions. You should be fine building the centos-08.0 example which points to the stream repos now. Let us know if there are further issues. Thanks
